### ISSUE TITLE
Issues09 - Faltando Referência ao Main no pom.xml

### ISSUE THREAD

**Issue by lukinhasgomes** [lucaskraus/projetocc8850#16]
Classe:
pom.xml

Severidade:
Alta

Classificação:
Inicialização/computação

Descrição:
No pom.xml não estava definido a main então o código não rodava.

Imagens:
![image](https://github.com/lucaskraus/projetocc8850/assets/99925705/4be38716-67c0-41eb-9452-b844a3b759c8)

![image](https://github.com/lucaskraus/projetocc8850/assets/99925705/e1cb5f68-757a-4a86-842e-0c336d8bf01e)

**Comment by luca-moraes** [comment]
Resolvido no commit 521b272 e aprovado nos testes rodados pelo CI.
